// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/assets_generator
// **************************************************************************
// ignore_for_file: constant_identifier_names

class Assets {
  const Assets._();

  /// {@macro assets_generator.assetsImagesDarkJPG.preview}
  static const String assetsImagesDarkJPG = 'assets/images/dark.JPG';

  /// {@macro assets_generator.assetsImagesLightJPG.preview}
  static const String assetsImagesLightJPG = 'assets/images/light.JPG';
}

final List<String> assetsArray = <String>[
  /// {@macro assets_generator.assetsImagesDarkJPG.preview}
  Assets.assetsImagesDarkJPG,

  /// {@macro assets_generator.assetsImagesLightJPG.preview}
  Assets.assetsImagesLightJPG,
];
